version: "3.1"

services: 
    magento2:
        build: ./magento
        container_name: magento2_nginx
        volumes:
            - ./web:/var/www/html
        depends_on: 
            - db
            - es01
        ports: 
            - "8001:80"
    es01:
        image: elasticsearch:7.12.1
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-magento2-cluster
            - discovery.type=single-node
        volumes:
            - ./es01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300
    db:
        image: mysql:8.0
        container_name: mysql_8.0   
        command: mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql_data:/var/lib/mysql
        env_file: 
            - env
        ports:
            - "3306:3306"